import type { ReactNode } from "react";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";

// Single source of truth for short jargon explanations. Keep entries
// concise — these render in a max-w-sm tooltip on hover. Add a new
// term by appending to the dictionary; the component looks up by the
// `term` prop or falls back to the literal child text when no `term`
// is supplied.
const GLOSSARY: Record<string, { title: string; body: string }> = {
  "ERC-7984": {
    title: "ERC-7984",
    body: "Confidential Fungible Token standard. Balances are stored as encrypted bytes32 handles; only ACL-permitted addresses can decrypt the underlying value. Co-authored by OpenZeppelin and Zama, finalized 2025-07.",
  },
  "ERC-3643": {
    title: "ERC-3643",
    body: "T-REX permissioned token standard. Enforces KYC + claim attestations on every transfer via the IdentityRegistry + ModularCompliance stack.",
  },
  "ERC-7540": {
    title: "ERC-7540",
    body: "Async Vault standard. Adapted here for ERC-7984 encrypted handle types — the canonical spec uses uint256, which is incompatible with bytes32 confidential amounts.",
  },
  Nox: {
    title: "iExec Nox",
    body: "TEE-based confidential execution layer. Runs the encryption + decryption ACL grants for ERC-7984 handles. Audited by Halborn, Arbitrum Sepolia testnet support since 2025-11.",
  },
  MEMO_ROLE: {
    title: "MEMO_ROLE",
    body: "AccessControl role on GroundVaultRegistry. Holders can call setMemo to anchor the keccak256 of a new impact memo to chain.",
  },
  OPERATOR_ROLE: {
    title: "OPERATOR_ROLE",
    body: "AccessControl role on GroundVaultCore. Holders can call processDeposit to advance a user's pending deposit to claimable.",
  },
  keccak256: {
    title: "keccak256",
    body: "Ethereum's standard cryptographic hash. Computed over the memo body and stored on chain so anyone can verify the rendered text matches what was anchored.",
  },
  ChainGPT: {
    title: "ChainGPT",
    body: "Web3-aware LLM. The Impact Risk Memo is generated by the general_assistant model from HUD CHAS cost-burden data, FRED treasury rate, and opportunity metadata.",
  },
  cUSDC: {
    title: "cUSDC (confidential USDC)",
    body: "ERC-7984 wrapper over MockUSDC. Wrap deposits 6-decimal mUSDC and emits an encrypted handle representing the same value, decryptable only via Nox ACL.",
  },
  mUSDC: {
    title: "mUSDC (mock USDC)",
    body: "Six-decimal mock ERC-20 used for testnet liquidity. Mintable by the deployer wallet only.",
  },
  handle: {
    title: "Encrypted handle",
    body: "Bytes32 reference to encrypted state. Every public chain reader sees the handle; only ACL-granted addresses can ask Nox for the decrypted value.",
  },
  ACL: {
    title: "Access Control List",
    body: "Nox-managed grant of decryption permission on a handle. Granted automatically on mint and on confidentialTransfer to the recipient address.",
  },
};

interface JargonProps {
  term?: keyof typeof GLOSSARY | string;
  children: ReactNode;
}

export function Jargon({ term, children }: JargonProps) {
  const key = (term ?? (typeof children === "string" ? children : "")) as string;
  const entry = GLOSSARY[key];
  if (!entry) {
    if (import.meta.env.DEV) {
      // eslint-disable-next-line no-console
      console.warn(
        `Jargon: no glossary entry for term ${JSON.stringify(key)} — child rendered as plain text`,
      );
    }
    return <>{children}</>;
  }
  return (
    <Tooltip>
      <TooltipTrigger asChild>
        <span className="border-b border-dotted border-muted-foreground/60 cursor-help">
          {children}
        </span>
      </TooltipTrigger>
      <TooltipContent side="top" className="max-w-sm">
        <div className="text-xs font-semibold mb-1">{entry.title}</div>
        <div className="text-[11px] text-muted-foreground leading-relaxed">{entry.body}</div>
      </TooltipContent>
    </Tooltip>
  );
}
